const SENTENCES = [
  "The morning light slipped through the kitchen window and warmed the wooden table.",
  "She poured a second cup of coffee and opened the notebook she had left unfinished.",
  "Outside, the street was quiet except for a bicycle rolling over wet pavement.",
  "He checked the clock, then packed the letters into a small canvas bag.",
  "The river followed the city for miles before turning toward the open fields.",
  "They waited under the station roof while the rain softened into a fine mist.",
  "A single lamp stayed on in the hallway, throwing a thin gold line across the floor.",
  "She wrote the names carefully, leaving space between each one as if they needed air.",
  "The old radio crackled once and then found a song from another decade.",
  "He remembered the path through the woods, even though the signs had changed.",
  "The bakery opened early, filling the block with the smell of bread and orange peel.",
  "A train passed in the distance, slow enough that its windows looked like lanterns.",
  "She folded the map along its worn creases and slipped it into her coat.",
  "The conversation paused, not from disagreement, but from the weight of what came next.",
  "Clouds gathered over the harbor, and the boats began to rock against the dock.",
  "He set the keys on the counter and listened to the house settle into evening.",
  "The library was almost empty, which made every page turn sound deliberate.",
  "She walked the long way home so the afternoon would last a little longer.",
  "A child counted the steps on the museum stairs and missed the last one on purpose.",
  "The garden survived the winter because someone had covered the roots with leaves.",
  "He wrote a short note, then crossed out the first sentence and started again.",
  "The cafe windows fogged as people came in from the cold with wet collars.",
  "She kept the photograph in a book she never finished, pressed between two quiet chapters.",
  "Night arrived without ceremony, just a gradual dimming of the shopfront lights.",
  "The road climbed until the town looked small enough to hold in one glance.",
  "He practiced the same phrase until his hands remembered it better than his mind.",
  "The letter arrived late, but the handwriting still felt immediate and close.",
  "They crossed the bridge in silence, watching the water catch pieces of the sky.",
  "A clock in the hallway struck the hour as if it were reminding the rooms to breathe.",
  "She left the window open so the curtains would move like a slow conversation.",
  "The market filled with voices, crates, and the bright disorder of fruit in season.",
  "He followed the coastline until the path became sand and the sand became tide.",
  "The first snow of the year made every rooftop look newly decided.",
  "She asked a simple question and waited, because waiting was part of the answer.",
  "The workshop smelled of pine, oil, and the patient dust of unfinished work.",
  "A stray cat watched from the alley as if it owned the entire evening.",
  "He turned the page, then realized he had been reading the same paragraph twice.",
  "The mountain road narrowed, and the trees closed in like a well-kept secret.",
  "She hung the coat by the door and stood still until the rain stopped dripping.",
  "The orchestra tuned in fragments, then gathered itself into a single breath.",
  "He packed the camera last, as if the rest of the trip depended on that one habit.",
  "The city at dawn looked unfinished, all steel and shadow waiting for color.",
  "They shared an umbrella that was slightly too small and laughed about it anyway.",
  "The typewriter sat on the desk like a machine that still believed in letters.",
  "She traced the coastline on the atlas and imagined the weather changing under her finger.",
  "A neighbor watered the plants after dark, humming something almost familiar.",
  "The ferry left on time, cutting a pale line through water the color of slate.",
  "He kept the receipt, not for the purchase, but for the date written in the corner.",
  "The classroom emptied slowly, chairs scraping, papers folding, voices dropping away.",
  "She stood at the edge of the field and watched the wind rewrite the grass.",
  "The old hotel still used brass keys, which made every return feel ceremonial.",
  "He spoke softly, as people do when a room has already decided to be quiet.",
  "The tide withdrew and left a scatter of shells that looked like discarded punctuation.",
  "She practiced until the sentence felt natural, then typed it without looking down.",
  "A bicycle bell rang twice at the corner, bright and unnecessary and perfect.",
  "The attic held boxes of postcards, none of them sent, all of them dated.",
  "He walked through the museum as if each painting were a door he might still open.",
  "The storm passed overnight, leaving the streets polished and strangely calm.",
  "She closed the laptop and let the room become a room again.",
  "The orchard rows ran straight until the hill made them hesitate.",
  "He counted the remaining matches and decided the evening still had enough light.",
  "The bookstore clerk recommended a novel by placing it on the counter without a speech.",
  "She remembered the recipe by smell more than by any written instruction.",
  "The clocktower was five minutes slow, which somehow made the square feel kinder.",
  "A moth kept returning to the same lamp, as if persistence were a kind of map.",
  "He signed the last page, then sat back and listened to the pen roll to a stop.",
  "The harbor bells rang when the fog came in, more warning than music.",
  "She packed the suitcase with more care than the trip itself seemed to require.",
  "The piano in the corner had one sticky key that everyone learned to forgive.",
  "He waited for the bus with a book open, though he had not turned a page.",
  "The hillside houses glowed in staggered rows, like a sentence written in windows.",
  "She kept walking because the road kept offering another reasonable reason to continue.",
  "The kitchen radio reported the weather as if it were gossip from a distant cousin.",
  "A pair of gloves lay on the bench, still shaped by the hands that had left them.",
  "He looked up from the letter and noticed that the afternoon had changed color.",
  "The chapel door closed softly, and the sound of outside traffic became theoretical.",
  "She practiced the greeting in her head until it no longer sounded like a performance.",
  "The snow melted from the roof in slow, irregular sentences of water.",
  "He took the long corridor because the short one always felt like an argument.",
  "The orchard ladder leaned against the same tree it had leaned against last year.",
  "She wrote in the margins, not to correct the book, but to keep it company.",
  "The evening train carried a few passengers and a great deal of leftover light.",
  "He set the metronome going and let the room learn the tempo before he began.",
  "The river ice cracked along a line that looked too straight to be accidental.",
  "She left a light on in the study, a small claim against the size of the house.",
  "The market closed, but the smell of citrus stayed in the street a little longer.",
  "A window opened upstairs, and a curtain reached out as if testing the weather.",
  "He folded the newspaper along the same crease his father had used.",
  "The path through the park was familiar enough that he could think about something else.",
  "She finished the paragraph, then read it aloud to see whether it still sounded true.",
  "Hi team, I have attached the revised agenda for tomorrow's planning meeting.",
  "Could you review the budget summary and share your feedback by Thursday afternoon?",
  "Thanks for flagging this issue; I will check the latest numbers and follow up.",
  "I am writing to confirm that the project handoff is scheduled for next Monday.",
  "Please let me know if you need anything else before we send the proposal.",
  "The client requested a shorter timeline, so we should discuss the available options.",
  "I have added the meeting notes to the shared folder for everyone to review.",
  "Would you be available for a quick call to discuss the launch plan?",
  "Thank you for your patience while we investigate the cause of the delay.",
  "The updated report includes the changes we discussed during this morning's review.",
  "Please reply when you have a chance so I can finalize the presentation.",
  "I will be out of the office on Friday, but I can respond to urgent messages.",
  "The team agreed to move the deadline and send a progress update by Wednesday.",
  "Could someone share the link to the latest version of the design brief?",
  "We should keep the email concise and include the decision at the top.",
  "Thanks for meeting today; I will send a summary with the next steps shortly.",
  "The new onboarding guide is ready, and comments are welcome before it is published.",
  "Good morning, I have a question about the figures in the quarterly forecast.",
  "I can take the first draft and post it here before the end of the day.",
  "Are we still on for the ten o'clock check in with the product group?",
  "I have shared the spreadsheet in this chat; please add your updates there.",
  "That works for me, and I will join the call a few minutes early.",
  "Could you send the slide deck before the meeting so we can review it?",
  "Quick update: the test passed, and the fix is ready for another review.",
  "I am stepping away for lunch, but please tag me if anything is urgent.",
  "Let's use this thread to collect questions before the customer presentation.",
  "I agree with the proposal, especially the plan to reduce manual follow up.",
  "Can we move our check in to the afternoon? I have a scheduling conflict.",
  "The shared notes capture the decisions, owners, and dates from today's discussion.",
  "I will take a look after this call and send you a clear answer.",
  "Please add your availability to the calendar invite so we can choose a time.",
  "The release is on track, and we will post another update after the final review.",
  "Thanks, everyone; the quick responses helped us resolve the issue before the deadline.",
  "abigus gandos",
];
